import type { GuideContent } from "@/types/content";

import bestPdfAppForBusiness from "@/content/pt-BR/guides/best-pdf-app-for-business";
import bestPdfAppForStudents from "@/content/pt-BR/guides/best-pdf-app-for-students";
import howToCompressPdf from "@/content/pt-BR/guides/how-to-compress-pdf";
import howToConvertJpgToPdf from "@/content/pt-BR/guides/how-to-convert-jpg-to-pdf";
import howToConvertPdfToJpg from "@/content/pt-BR/guides/how-to-convert-pdf-to-jpg";
import howToConvertPdfToPng from "@/content/pt-BR/guides/how-to-convert-pdf-to-png";
import howToConvertPdfToWord from "@/content/pt-BR/guides/how-to-convert-pdf-to-word";
import howToConvertPhotosToPdfOnAndroid from "@/content/pt-BR/guides/how-to-convert-photos-to-pdf-on-android";
import howToConvertPhotosToPdfOnIphone from "@/content/pt-BR/guides/how-to-convert-photos-to-pdf-on-iphone";
import howToConvertPngToPdf from "@/content/pt-BR/guides/how-to-convert-png-to-pdf";
import howToConvertScannedDocumentsToPdf from "@/content/pt-BR/guides/how-to-convert-scanned-documents-to-pdf";
import howToConvertWebpToPdf from "@/content/pt-BR/guides/how-to-convert-webp-to-pdf";
import howToConvertWordToPdf from "@/content/pt-BR/guides/how-to-convert-word-to-pdf";
import howToEditPdfOnAndroid from "@/content/pt-BR/guides/how-to-edit-pdf-on-android";
import howToEditPdfOnIphone from "@/content/pt-BR/guides/how-to-edit-pdf-on-iphone";
import howToMergePdfFiles from "@/content/pt-BR/guides/how-to-merge-pdf-files";
import howToProtectPdfFile from "@/content/pt-BR/guides/how-to-protect-pdf-file";
import howToScanDocumentsToPdf from "@/content/pt-BR/guides/how-to-scan-documents-to-pdf";
import howToSignPdfOnPhone from "@/content/pt-BR/guides/how-to-sign-pdf-on-phone";
import pdfVsDocx from "@/content/pt-BR/guides/pdf-vs-docx";

/**
 * Brazilian Portuguese guides, keyed by the **English** slug.
 *
 * GENERATED by scripts/i18n/gen-guide-index.mjs — do not edit by hand.
 *
 * The key and each record's `slug` are the English slug on purpose: the
 * Portuguese URL lives in the route manifest and nowhere else, so the two
 * can never disagree. `related` and `parentHub` paths stay English too and
 * are translated at render time — see src/content/registry.ts.
 */
export const GUIDES_PT_BR: Record<string, GuideContent> = {
  "best-pdf-app-for-business": bestPdfAppForBusiness,
  "best-pdf-app-for-students": bestPdfAppForStudents,
  "how-to-compress-pdf": howToCompressPdf,
  "how-to-convert-jpg-to-pdf": howToConvertJpgToPdf,
  "how-to-convert-pdf-to-jpg": howToConvertPdfToJpg,
  "how-to-convert-pdf-to-png": howToConvertPdfToPng,
  "how-to-convert-pdf-to-word": howToConvertPdfToWord,
  "how-to-convert-photos-to-pdf-on-android": howToConvertPhotosToPdfOnAndroid,
  "how-to-convert-photos-to-pdf-on-iphone": howToConvertPhotosToPdfOnIphone,
  "how-to-convert-png-to-pdf": howToConvertPngToPdf,
  "how-to-convert-scanned-documents-to-pdf": howToConvertScannedDocumentsToPdf,
  "how-to-convert-webp-to-pdf": howToConvertWebpToPdf,
  "how-to-convert-word-to-pdf": howToConvertWordToPdf,
  "how-to-edit-pdf-on-android": howToEditPdfOnAndroid,
  "how-to-edit-pdf-on-iphone": howToEditPdfOnIphone,
  "how-to-merge-pdf-files": howToMergePdfFiles,
  "how-to-protect-pdf-file": howToProtectPdfFile,
  "how-to-scan-documents-to-pdf": howToScanDocumentsToPdf,
  "how-to-sign-pdf-on-phone": howToSignPdfOnPhone,
  "pdf-vs-docx": pdfVsDocx,
};
