import { urlsetXml, XML_HEADERS } from "@/lib/sitemap";

// GENERATED by scripts/i18n/gen-sitemap-routes.mjs — do not edit by hand.
export const dynamic = "force-static";

export function GET() {
  return new Response(urlsetXml("tools", "ru"), { headers: XML_HEADERS });
}
