import type {
  KnowledgeCluster,
  KnowledgeDifficulty,
  KnowledgeSearchIntent,
} from "@/types/content";

export interface ManifestEntry {
  slug: string;
  h1: string;
  cluster: KnowledgeCluster;
  searchIntent: KnowledgeSearchIntent;
  difficulty: KnowledgeDifficulty;
  parentConcept?: string;
}

/**
 * Deduplicated Phase A topic list — the single source of truth for slugs and
 * graph anchors. Every slug is a reference/definitional concept that does NOT
 * duplicate an existing how-to guide, tool, hub or compare route. Skipped
 * candidates are logged in
 * docs/superpowers/plans/2026-07-04-phase-a-topic-manifest.md.
 *
 * Authored as per-cluster groups (with default searchIntent/difficulty) to stay
 * DRY, then flattened to MANIFEST below.
 */

type Row = {
  slug: string;
  h1: string;
  searchIntent?: KnowledgeSearchIntent;
  difficulty?: KnowledgeDifficulty;
  parentConcept?: string;
};

type Group = {
  cluster: KnowledgeCluster;
  defaultIntent: KnowledgeSearchIntent;
  defaultDifficulty: KnowledgeDifficulty;
  anchor: string; // default parentConcept for rows without an explicit one
  rows: Row[];
};

const GROUPS: Group[] = [
  {
    cluster: "foundations",
    defaultIntent: "concept",
    defaultDifficulty: "Intermediate",
    anchor: "portable-document-format",
    rows: [
      { slug: "portable-document-format", h1: "Portable Document Format (PDF)", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "history-of-pdf", h1: "The History of PDF", searchIntent: "history", difficulty: "Beginner" },
      { slug: "iso-32000", h1: "ISO 32000", searchIntent: "standard" },
      { slug: "pdf-versions", h1: "PDF Versions", searchIntent: "specification", difficulty: "Beginner" },
      { slug: "pdf-1-4", h1: "PDF 1.4", searchIntent: "specification" },
      { slug: "pdf-1-5", h1: "PDF 1.5", searchIntent: "specification" },
      { slug: "pdf-1-6", h1: "PDF 1.6", searchIntent: "specification" },
      { slug: "pdf-1-7", h1: "PDF 1.7", searchIntent: "specification" },
      { slug: "pdf-2-0", h1: "PDF 2.0", searchIntent: "specification" },
      { slug: "pdf-file-structure", h1: "PDF File Structure", difficulty: "Beginner" },
      { slug: "pdf-objects", h1: "PDF Objects", parentConcept: "pdf-file-structure" },
      { slug: "pdf-indirect-objects", h1: "Indirect Objects in PDF", difficulty: "Advanced", parentConcept: "pdf-objects" },
      { slug: "pdf-name-objects", h1: "PDF Name Objects", parentConcept: "pdf-objects" },
      { slug: "pdf-string-objects", h1: "PDF String Objects", parentConcept: "pdf-objects" },
      { slug: "pdf-stream-objects", h1: "PDF Stream Objects", parentConcept: "pdf-objects" },
      { slug: "pdf-dictionary", h1: "PDF Dictionary Objects", parentConcept: "pdf-objects" },
      { slug: "pdf-array-objects", h1: "PDF Array Objects", parentConcept: "pdf-objects" },
      { slug: "pdf-object-streams", h1: "PDF Object Streams", searchIntent: "specification", difficulty: "Advanced", parentConcept: "pdf-file-structure" },
      { slug: "pdf-cross-reference-table", h1: "The PDF Cross-Reference Table", difficulty: "Advanced", parentConcept: "pdf-file-structure" },
      { slug: "pdf-xref-streams", h1: "PDF Cross-Reference Streams", difficulty: "Advanced", parentConcept: "pdf-cross-reference-table" },
      { slug: "pdf-trailer", h1: "The PDF Trailer", difficulty: "Advanced", parentConcept: "pdf-file-structure" },
      { slug: "pdf-document-catalog", h1: "The PDF Document Catalog", parentConcept: "pdf-file-structure" },
      { slug: "pdf-page-tree", h1: "The PDF Page Tree", parentConcept: "pdf-document-catalog" },
      { slug: "pdf-content-streams", h1: "PDF Content Streams", parentConcept: "pdf-file-structure" },
      { slug: "pdf-operators", h1: "PDF Content Stream Operators", difficulty: "Advanced", parentConcept: "pdf-content-streams" },
      { slug: "pdf-header", h1: "The PDF File Header", difficulty: "Beginner", parentConcept: "pdf-file-structure" },
      { slug: "pdf-incremental-updates", h1: "Incremental Updates in PDF", difficulty: "Advanced", parentConcept: "pdf-file-structure" },
      { slug: "linearized-pdf", h1: "Linearized PDF (Fast Web View)", searchIntent: "specification" },
      { slug: "pdf-coordinate-system", h1: "The PDF Coordinate System" },
      { slug: "pdf-vs-postscript", h1: "PDF vs PostScript", searchIntent: "comparison" },
    ],
  },
  {
    cluster: "standards",
    defaultIntent: "standard",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-standards-overview",
    rows: [
      { slug: "pdf-standards-overview", h1: "The PDF Standards Family", searchIntent: "concept", difficulty: "Beginner", parentConcept: "iso-32000" },
      { slug: "pdf-a", h1: "PDF/A" },
      { slug: "pdf-a-1", h1: "PDF/A-1", parentConcept: "pdf-a" },
      { slug: "pdf-a-2", h1: "PDF/A-2", parentConcept: "pdf-a" },
      { slug: "pdf-a-3", h1: "PDF/A-3", parentConcept: "pdf-a" },
      { slug: "pdf-a-4", h1: "PDF/A-4", parentConcept: "pdf-a" },
      { slug: "pdf-a-conformance-levels", h1: "PDF/A Conformance Levels", searchIntent: "concept", parentConcept: "pdf-a" },
      { slug: "pdf-a-validation", h1: "PDF/A Validation", searchIntent: "concept", parentConcept: "pdf-a" },
      { slug: "pdf-a-metadata-requirements", h1: "PDF/A Metadata Requirements", difficulty: "Advanced", parentConcept: "pdf-a" },
      { slug: "pdf-a-font-embedding", h1: "Font Embedding in PDF/A", difficulty: "Advanced", parentConcept: "pdf-a" },
      { slug: "verapdf", h1: "veraPDF", searchIntent: "concept", parentConcept: "pdf-a-validation" },
      { slug: "pdf-x", h1: "PDF/X" },
      { slug: "pdf-x-1a", h1: "PDF/X-1a", parentConcept: "pdf-x" },
      { slug: "pdf-x-3", h1: "PDF/X-3", parentConcept: "pdf-x" },
      { slug: "pdf-x-4", h1: "PDF/X-4", parentConcept: "pdf-x" },
      { slug: "pdf-output-intent", h1: "PDF Output Intents", searchIntent: "concept", difficulty: "Advanced", parentConcept: "pdf-x" },
      { slug: "pdf-x-trapping", h1: "Trapping in PDF/X", difficulty: "Advanced", parentConcept: "pdf-x" },
      { slug: "pdf-ua", h1: "PDF/UA" },
      { slug: "pdf-ua-1", h1: "PDF/UA-1", parentConcept: "pdf-ua" },
      { slug: "pdf-e", h1: "PDF/E" },
      { slug: "pdf-vt", h1: "PDF/VT" },
      { slug: "pdf-conformance-levels", h1: "What Conformance Levels Mean in PDF", searchIntent: "concept" },
      { slug: "pdf-a-vs-pdf-x", h1: "PDF/A vs PDF/X", searchIntent: "comparison" },
      { slug: "pdf-a-vs-pdf-ua", h1: "PDF/A vs PDF/UA", searchIntent: "comparison" },
      { slug: "why-standardize-pdf", h1: "Why PDF Was Standardized", searchIntent: "concept", difficulty: "Beginner" },
    ],
  },
  {
    cluster: "text-fonts",
    defaultIntent: "concept",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-fonts",
    rows: [
      { slug: "pdf-fonts", h1: "How Fonts Work in PDF", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "font-embedding", h1: "Font Embedding in PDF" },
      { slug: "font-subsetting", h1: "Font Subsetting in PDF" },
      { slug: "non-embedded-fonts", h1: "Non-Embedded Fonts in PDF" },
      { slug: "standard-14-fonts", h1: "The Standard 14 PDF Fonts" },
      { slug: "type-1-fonts", h1: "Type 1 Fonts in PDF", difficulty: "Advanced" },
      { slug: "truetype-fonts-in-pdf", h1: "TrueType Fonts in PDF" },
      { slug: "opentype-fonts-in-pdf", h1: "OpenType Fonts in PDF" },
      { slug: "type-0-fonts", h1: "Type 0 (Composite) Fonts", difficulty: "Advanced" },
      { slug: "type-3-fonts", h1: "Type 3 Fonts in PDF", difficulty: "Advanced" },
      { slug: "cid-fonts", h1: "CID-Keyed Fonts", difficulty: "Advanced" },
      { slug: "composite-vs-simple-fonts", h1: "Composite vs Simple Fonts", searchIntent: "comparison" },
      { slug: "cmap", h1: "CMaps in PDF", difficulty: "Advanced" },
      { slug: "character-encoding-in-pdf", h1: "Character Encoding in PDF" },
      { slug: "winansiencoding", h1: "WinAnsiEncoding", difficulty: "Advanced" },
      { slug: "standard-encoding", h1: "StandardEncoding in PDF", difficulty: "Advanced" },
      { slug: "tounicode-cmap", h1: "ToUnicode CMaps", difficulty: "Advanced" },
      { slug: "glyph", h1: "Glyphs in PDF", searchIntent: "definition", difficulty: "Beginner" },
      { slug: "font-descriptor", h1: "The PDF Font Descriptor", difficulty: "Advanced" },
      { slug: "font-flags", h1: "PDF Font Flags", difficulty: "Advanced" },
      { slug: "font-substitution", h1: "Font Substitution in PDF" },
      { slug: "text-rendering-modes", h1: "PDF Text Rendering Modes", searchIntent: "rendering" },
      { slug: "pdf-text-extraction", h1: "How Text Extraction From PDF Works" },
      { slug: "cjk-fonts-in-pdf", h1: "CJK Fonts in PDF", difficulty: "Advanced" },
      { slug: "embedded-font-programs", h1: "Embedded Font Programs", difficulty: "Advanced" },
      { slug: "text-showing-operators", h1: "PDF Text-Showing Operators", searchIntent: "specification", difficulty: "Advanced" },
    ],
  },
  {
    cluster: "graphics-color",
    defaultIntent: "concept",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-color",
    rows: [
      { slug: "pdf-color", h1: "Color Spaces in PDF", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "devicergb", h1: "DeviceRGB Color in PDF" },
      { slug: "devicecmyk", h1: "DeviceCMYK Color in PDF" },
      { slug: "devicegray", h1: "DeviceGray Color in PDF" },
      { slug: "calrgb-and-calgray", h1: "CalRGB and CalGray Color", difficulty: "Advanced" },
      { slug: "lab-color-in-pdf", h1: "Lab Color in PDF", difficulty: "Advanced" },
      { slug: "icc-based-color", h1: "ICC-Based Color in PDF", difficulty: "Advanced" },
      { slug: "icc-profiles-in-pdf", h1: "ICC Profiles in PDF" },
      { slug: "indexed-color", h1: "Indexed Color in PDF" },
      { slug: "separation-color", h1: "Separation Color in PDF", difficulty: "Advanced" },
      { slug: "devicen-color", h1: "DeviceN Color in PDF", difficulty: "Advanced" },
      { slug: "spot-colors", h1: "Spot Colors in PDF" },
      { slug: "color-management-in-pdf", h1: "Color Management in PDF" },
      { slug: "rendering-intent", h1: "Rendering Intents in PDF", searchIntent: "rendering", difficulty: "Advanced" },
      { slug: "overprint", h1: "Overprint in PDF", difficulty: "Advanced" },
      { slug: "pdf-transparency", h1: "Transparency in PDF" },
      { slug: "transparency-groups", h1: "Transparency Groups", difficulty: "Advanced" },
      { slug: "blend-modes", h1: "Blend Modes in PDF" },
      { slug: "soft-masks", h1: "Soft Masks in PDF", difficulty: "Advanced" },
      { slug: "pdf-graphics-state", h1: "The PDF Graphics State", difficulty: "Advanced" },
      { slug: "pdf-vector-graphics", h1: "Vector Graphics in PDF", searchIntent: "rendering", difficulty: "Beginner" },
      { slug: "clipping-paths", h1: "Clipping Paths in PDF" },
      { slug: "pdf-shadings", h1: "Shadings and Gradients in PDF", searchIntent: "rendering", difficulty: "Advanced" },
      { slug: "pdf-patterns", h1: "Pattern Objects in PDF", difficulty: "Advanced" },
      { slug: "image-xobjects", h1: "Image XObjects in PDF", difficulty: "Advanced" },
      { slug: "form-xobjects", h1: "Form XObjects in PDF", difficulty: "Advanced" },
    ],
  },
  {
    cluster: "images-compression",
    defaultIntent: "concept",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-compression",
    rows: [
      { slug: "pdf-compression", h1: "How PDF Compression Works", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "pdf-filters", h1: "PDF Stream Filters" },
      { slug: "flate-decode", h1: "FlateDecode Compression" },
      { slug: "lzw-decode", h1: "LZWDecode Compression", difficulty: "Advanced" },
      { slug: "ascii85-decode", h1: "ASCII85Decode Encoding", difficulty: "Advanced" },
      { slug: "asciihex-decode", h1: "ASCIIHexDecode Encoding", difficulty: "Advanced" },
      { slug: "runlength-decode", h1: "RunLengthDecode Compression", difficulty: "Advanced" },
      { slug: "dct-decode-jpeg", h1: "DCTDecode (JPEG in PDF)" },
      { slug: "jpx-decode-jpeg2000", h1: "JPXDecode (JPEG 2000 in PDF)", difficulty: "Advanced" },
      { slug: "ccittfax-decode", h1: "CCITTFaxDecode Compression", difficulty: "Advanced" },
      { slug: "jbig2-decode", h1: "JBIG2 Compression in PDF", difficulty: "Advanced" },
      { slug: "image-downsampling", h1: "Image Downsampling in PDF" },
      { slug: "image-resolution-in-pdf", h1: "Image Resolution in PDF", difficulty: "Beginner" },
      { slug: "bits-per-component", h1: "Bits Per Component in PDF Images", difficulty: "Advanced" },
      { slug: "image-color-depth", h1: "Image Color Depth in PDF" },
      { slug: "lossy-vs-lossless-pdf-compression", h1: "Lossy vs Lossless PDF Compression", searchIntent: "comparison" },
      { slug: "pdf-optimization", h1: "PDF Optimization" },
      { slug: "pdf-file-size-factors", h1: "What Makes a PDF Large", searchIntent: "concept", difficulty: "Beginner" },
      { slug: "object-stream-compression", h1: "Object Stream Compression", difficulty: "Advanced" },
      { slug: "image-interpolation", h1: "Image Interpolation in PDF", difficulty: "Advanced" },
      { slug: "image-masks", h1: "Image Masks in PDF", difficulty: "Advanced" },
      { slug: "stencil-masks", h1: "Stencil Masks in PDF", difficulty: "Advanced" },
      { slug: "color-key-masking", h1: "Color Key Masking in PDF", difficulty: "Advanced" },
      { slug: "inline-images", h1: "Inline Images in PDF", difficulty: "Advanced" },
      { slug: "image-soft-masks", h1: "Image Soft Masks (SMask)", difficulty: "Advanced" },
      { slug: "predictor-functions", h1: "Predictor Functions in PDF Compression", difficulty: "Advanced" },
    ],
  },
  {
    cluster: "interactivity",
    defaultIntent: "concept",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-interactive-features",
    rows: [
      { slug: "pdf-interactive-features", h1: "Interactive Features in PDF", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "acroform", h1: "AcroForm (PDF Interactive Forms)" },
      { slug: "xfa-forms", h1: "XFA Forms", difficulty: "Advanced" },
      { slug: "pdf-form-fields", h1: "PDF Form Fields", parentConcept: "acroform" },
      { slug: "text-form-fields", h1: "Text Form Fields", parentConcept: "pdf-form-fields" },
      { slug: "checkbox-form-fields", h1: "Checkbox Form Fields", parentConcept: "pdf-form-fields" },
      { slug: "radio-button-fields", h1: "Radio Button Fields", parentConcept: "pdf-form-fields" },
      { slug: "choice-fields", h1: "Choice Fields (Lists and Combos)", parentConcept: "pdf-form-fields" },
      { slug: "signature-fields", h1: "Signature Fields in PDF", parentConcept: "pdf-form-fields" },
      { slug: "form-field-flags", h1: "PDF Form Field Flags", difficulty: "Advanced", parentConcept: "pdf-form-fields" },
      { slug: "form-flattening", h1: "PDF Form Flattening" },
      { slug: "form-calculation", h1: "Form Field Calculations", difficulty: "Advanced" },
      { slug: "javascript-in-pdf", h1: "JavaScript in PDF", difficulty: "Advanced" },
      { slug: "pdf-annotations", h1: "PDF Annotations" },
      { slug: "annotation-types", h1: "Types of PDF Annotations", parentConcept: "pdf-annotations" },
      { slug: "link-annotations", h1: "Link Annotations in PDF", parentConcept: "pdf-annotations" },
      { slug: "markup-annotations", h1: "Markup Annotations in PDF", parentConcept: "pdf-annotations" },
      { slug: "widget-annotations", h1: "Widget Annotations in PDF", difficulty: "Advanced", parentConcept: "pdf-annotations" },
      { slug: "popup-annotations", h1: "Popup Annotations in PDF", parentConcept: "pdf-annotations" },
      { slug: "appearance-streams", h1: "Appearance Streams in PDF", difficulty: "Advanced" },
      { slug: "pdf-actions", h1: "PDF Actions" },
      { slug: "named-destinations", h1: "Named Destinations in PDF" },
      { slug: "pdf-bookmarks", h1: "PDF Bookmarks" },
      { slug: "pdf-outlines", h1: "The PDF Outline Tree", parentConcept: "pdf-bookmarks" },
      { slug: "fdf-and-xfdf", h1: "FDF and XFDF Form Data", difficulty: "Advanced" },
    ],
  },
  {
    cluster: "security",
    defaultIntent: "security",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-security-model",
    rows: [
      { slug: "pdf-security-model", h1: "The PDF Security Model", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "pdf-encryption", h1: "PDF Encryption" },
      { slug: "standard-security-handler", h1: "The Standard Security Handler", difficulty: "Advanced" },
      { slug: "rc4-encryption", h1: "RC4 Encryption in PDF", difficulty: "Advanced" },
      { slug: "aes-128-encryption", h1: "AES-128 Encryption in PDF", difficulty: "Advanced" },
      { slug: "aes-256-encryption", h1: "AES-256 Encryption in PDF", difficulty: "Advanced" },
      { slug: "public-key-security", h1: "Public-Key Security in PDF", difficulty: "Advanced" },
      { slug: "user-vs-owner-password", h1: "User vs Owner Password", searchIntent: "comparison" },
      { slug: "pdf-permission-flags", h1: "PDF Permission Flags" },
      { slug: "encryption-dictionary", h1: "The PDF Encryption Dictionary", difficulty: "Advanced" },
      { slug: "pdf-redaction", h1: "PDF Redaction" },
      { slug: "pdf-digital-signatures", h1: "PDF Digital Signatures" },
      { slug: "approval-vs-certification-signatures", h1: "Approval vs Certification Signatures", searchIntent: "comparison", difficulty: "Advanced" },
      { slug: "pki-in-pdf", h1: "Public Key Infrastructure in PDF", difficulty: "Advanced" },
      { slug: "pades", h1: "PAdES (PDF Advanced Electronic Signatures)", searchIntent: "standard", difficulty: "Advanced" },
      { slug: "cades-in-pdf", h1: "CAdES Signatures in PDF", difficulty: "Advanced" },
      { slug: "timestamp-signatures", h1: "Timestamp Signatures in PDF", difficulty: "Advanced" },
      { slug: "ltv-signatures", h1: "Long-Term Validation (LTV) Signatures", difficulty: "Advanced" },
      { slug: "document-security-store", h1: "The Document Security Store (DSS)", difficulty: "Advanced" },
      { slug: "signature-appearance", h1: "Signature Appearances in PDF" },
      { slug: "signature-validation", h1: "How PDF Signature Validation Works" },
      { slug: "hash-algorithms-in-pdf", h1: "Hash Algorithms in PDF Signatures", difficulty: "Advanced" },
      { slug: "tamper-evidence-in-pdf", h1: "Tamper Evidence in Signed PDFs" },
      { slug: "pdf-drm", h1: "DRM and PDF", searchIntent: "concept" },
      { slug: "password-vs-encryption", h1: "Password Protection vs Encryption", searchIntent: "comparison", difficulty: "Beginner" },
      { slug: "electronic-vs-digital-signature", h1: "Electronic vs Digital Signature", searchIntent: "comparison" },
    ],
  },
  {
    cluster: "accessibility",
    defaultIntent: "accessibility",
    defaultDifficulty: "Intermediate",
    anchor: "tagged-pdf",
    rows: [
      { slug: "tagged-pdf", h1: "Tagged PDF", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "pdf-structure-tree", h1: "The PDF Structure Tree", difficulty: "Advanced" },
      { slug: "structure-elements", h1: "PDF Structure Elements", difficulty: "Advanced", parentConcept: "pdf-structure-tree" },
      { slug: "marked-content", h1: "Marked Content in PDF", difficulty: "Advanced" },
      { slug: "marked-content-id", h1: "Marked Content IDs (MCID)", difficulty: "Advanced", parentConcept: "marked-content" },
      { slug: "logical-structure", h1: "Logical Structure in PDF", difficulty: "Advanced" },
      { slug: "reading-order", h1: "Reading Order in PDF" },
      { slug: "pdf-alt-text", h1: "Alternative Text in PDF" },
      { slug: "role-mapping", h1: "Role Mapping in Tagged PDF", difficulty: "Advanced" },
      { slug: "standard-structure-types", h1: "Standard Structure Types in PDF", difficulty: "Advanced" },
      { slug: "artifact-marking", h1: "Artifacts in Tagged PDF", difficulty: "Advanced" },
      { slug: "table-tagging-in-pdf", h1: "Table Tagging in PDF", difficulty: "Advanced" },
      { slug: "list-tagging-in-pdf", h1: "List Tagging in PDF", difficulty: "Advanced" },
      { slug: "heading-structure-in-pdf", h1: "Heading Structure in PDF" },
      { slug: "language-specification-in-pdf", h1: "Language Specification in PDF" },
      { slug: "accessible-pdf-forms", h1: "Accessible PDF Forms" },
      { slug: "wcag-and-pdf", h1: "WCAG and PDF", searchIntent: "standard" },
      { slug: "section-508-and-pdf", h1: "Section 508 and PDF", searchIntent: "standard" },
      { slug: "screen-readers-and-pdf", h1: "Screen Readers and PDF", difficulty: "Beginner" },
      { slug: "pdf-accessibility-checking", h1: "Checking PDF Accessibility" },
      { slug: "untagged-pdf", h1: "Untagged PDF", searchIntent: "concept", difficulty: "Beginner" },
      { slug: "well-tagged-pdf", h1: "What Makes a Well-Tagged PDF", difficulty: "Advanced" },
    ],
  },
  {
    cluster: "metadata-tooling",
    defaultIntent: "metadata",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-metadata",
    rows: [
      { slug: "pdf-metadata", h1: "PDF Metadata", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "document-information-dictionary", h1: "The Document Information Dictionary", difficulty: "Advanced" },
      { slug: "xmp-metadata", h1: "XMP Metadata in PDF" },
      { slug: "xmp-vs-info-dictionary", h1: "XMP vs the Info Dictionary", searchIntent: "comparison", difficulty: "Advanced" },
      { slug: "custom-metadata-in-pdf", h1: "Custom Metadata in PDF", difficulty: "Advanced" },
      { slug: "pdf-page-labels", h1: "PDF Page Labels" },
      { slug: "searchable-pdf", h1: "Searchable PDF", searchIntent: "concept", difficulty: "Beginner" },
      { slug: "image-only-pdf", h1: "Image-Only PDF", searchIntent: "concept", difficulty: "Beginner" },
      { slug: "pdf-ocr", h1: "OCR and PDF", searchIntent: "concept" },
      { slug: "text-layer-in-pdf", h1: "The Text Layer in a Scanned PDF" },
      { slug: "pdf-thumbnails", h1: "PDF Page Thumbnails" },
      { slug: "embedded-files-in-pdf", h1: "Embedded Files in PDF", difficulty: "Advanced" },
      { slug: "pdf-portfolios", h1: "PDF Portfolios" },
      { slug: "associated-files-in-pdf", h1: "Associated Files in PDF", difficulty: "Advanced" },
      { slug: "pdf-validation", h1: "PDF Validation", searchIntent: "concept" },
      { slug: "pdf-repair", h1: "How PDF Repair Works", searchIntent: "concept" },
      { slug: "pdf-comparison", h1: "How PDF Comparison Works", searchIntent: "concept" },
      { slug: "document-properties", h1: "PDF Document Properties", searchIntent: "concept", difficulty: "Beginner" },
      { slug: "pdf-file-identifiers", h1: "PDF File Identifiers", difficulty: "Advanced" },
      { slug: "pdf-magic-number", h1: "The PDF File Signature", difficulty: "Advanced" },
      { slug: "pdf-mime-type", h1: "The PDF MIME Type", searchIntent: "definition", difficulty: "Beginner" },
      { slug: "pdf-metadata-standards", h1: "Metadata Standards Used in PDF", searchIntent: "standard", difficulty: "Advanced" },
    ],
  },
  {
    cluster: "print-geometry",
    defaultIntent: "printing",
    defaultDifficulty: "Intermediate",
    anchor: "pdf-page-geometry",
    rows: [
      { slug: "pdf-page-geometry", h1: "PDF Page Geometry", searchIntent: "definition", difficulty: "Beginner", parentConcept: "" },
      { slug: "pdf-page-boxes", h1: "PDF Page Boxes", parentConcept: "pdf-page-geometry" },
      { slug: "mediabox", h1: "MediaBox in PDF", parentConcept: "pdf-page-boxes" },
      { slug: "cropbox", h1: "CropBox in PDF", parentConcept: "pdf-page-boxes" },
      { slug: "bleedbox", h1: "BleedBox in PDF", difficulty: "Advanced", parentConcept: "pdf-page-boxes" },
      { slug: "trimbox", h1: "TrimBox in PDF", difficulty: "Advanced", parentConcept: "pdf-page-boxes" },
      { slug: "artbox", h1: "ArtBox in PDF", difficulty: "Advanced", parentConcept: "pdf-page-boxes" },
      { slug: "pdf-page-size", h1: "PDF Page Sizes", searchIntent: "concept", difficulty: "Beginner" },
      { slug: "pdf-page-orientation", h1: "PDF Page Orientation", difficulty: "Beginner" },
      { slug: "pdf-page-rotation", h1: "PDF Page Rotation" },
      { slug: "user-space-and-device-space", h1: "User Space and Device Space", searchIntent: "rendering", difficulty: "Advanced" },
      { slug: "pdf-units-and-measurements", h1: "Units and Measurements in PDF", difficulty: "Beginner" },
      { slug: "optional-content-groups", h1: "Optional Content Groups (PDF Layers)", difficulty: "Advanced" },
      { slug: "pdf-layers", h1: "PDF Layers", searchIntent: "concept", parentConcept: "optional-content-groups" },
      { slug: "pdf-preflight", h1: "PDF Preflight", searchIntent: "concept" },
      { slug: "print-production-with-pdf", h1: "Print Production With PDF", searchIntent: "workflow" },
      { slug: "trapping", h1: "Trapping in Print Production", difficulty: "Advanced" },
      { slug: "bleed-and-crop-marks", h1: "Bleed and Crop Marks in PDF" },
      { slug: "pdf-printing-pipeline", h1: "How a PDF Is Printed", searchIntent: "rendering" },
      { slug: "press-ready-pdf", h1: "What Makes a Press-Ready PDF", searchIntent: "workflow" },
      { slug: "pdf-imposition", h1: "PDF Imposition", difficulty: "Advanced" },
      { slug: "pdf-page-scaling", h1: "PDF Page Scaling When Printing", difficulty: "Beginner" },
    ],
  },
];

export const MANIFEST: ManifestEntry[] = GROUPS.flatMap((g) =>
  g.rows.map((r) => ({
    slug: r.slug,
    h1: r.h1,
    cluster: g.cluster,
    searchIntent: r.searchIntent ?? g.defaultIntent,
    difficulty: r.difficulty ?? g.defaultDifficulty,
    // "" means "no parent" (cluster anchors); undefined falls back to the anchor.
    parentConcept:
      r.parentConcept === ""
        ? undefined
        : (r.parentConcept ?? g.anchor),
  })),
);
