import type { KnowledgeContent } from "@/types/content";

const content: KnowledgeContent = {
  "slug": "artifact-marking",
  "h1": "Artifacts in Tagged PDF",
  "cluster": "accessibility",
  "aliases": [
    "Artifact tag",
    "Artifact marking",
    "PDF artifacts",
    "Pagination artifacts",
    "Marked-content artifacts"
  ],
  "definition": "In a tagged PDF, artifacts are pieces of page content — such as running headers, page numbers and decorative rules — explicitly marked as carrying no logical meaning so assistive technology can ignore them.",
  "description": "Artifacts mark page furniture — headers, footers, page numbers and decoration — so a tagged PDF keeps it out of the reading order and away from assistive technology.",
  "searchIntent": "accessibility",
  "difficulty": "Advanced",
  "updated": "2026-07-04",
  "reviewed": "2026-07-04",
  "intro": [
    "A tagged PDF sorts everything drawn on a page into two buckets. Some of it is real content — the words, headings, images and tables that carry the document's meaning — and this content is wired into the logical structure so tools can read it in order. The rest is page furniture: the running header repeated at the top of every page, the folio (page number) at the foot, a decorative rule under a title, or a faint background watermark. That second category is what PDF calls artifacts.",
    "Artifacts are not hidden or deleted. They still print and still appear on screen exactly as before. What marking something as an artifact does is declare that it is not part of the author's logical content, so it should be skipped by assistive technology, by reflow, and by content-repurposing operations. A screen reader that announced 'Page 7 of 24' at the top and bottom of every single page would be exhausting to listen to; artifact marking is how that noise is kept out of the spoken reading order.",
    "Artifact marking is one specific use of PDF's marked-content facility, and it is a cornerstone of what makes a PDF well tagged. The guiding principle behind an accessible PDF is that every mark on the page must be accounted for as either meaningful content (connected to the structure tree) or as an artifact — nothing is allowed to fall in between."
  ],
  "sections": [
    {
      "heading": "Real content versus artifacts",
      "body": [
        "Tagged PDF draws a line between content that means something and content that is merely presentational or mechanical. Real content — a paragraph, a list item, a photograph, a data cell — is enclosed in a marked-content sequence that is linked to an element in the document's structure tree, so an assistive tool can find it, place it in reading order, and describe it. Artifacts are everything else that was placed on the page by the layout or production process rather than by the meaning of the document.",
        "Typical artifacts include running headers and footers, page numbers, decorative lines and boxes, column separators, the ruled grid of a table (as opposed to the cell contents), background tints or watermarks, and printer's marks like crop or registration targets. Marking these as artifacts tells software that they can be safely ignored when extracting text, reflowing the page to a small screen, or reading the document aloud."
      ]
    },
    {
      "heading": "How artifacts are marked in the content stream",
      "body": [
        "Artifacts are identified inside the page's content stream using the same marked-content operators that carry structural content: a sequence begins with BMC or BDC and ends with EMC. The distinguishing feature is the tag name Artifact. A simple artifact is opened with the Artifact tag and BMC; when extra information is attached, BDC is used with a property-list dictionary describing the artifact.",
        "Crucially, an artifact's marked-content sequence is never given a marked-content identifier (MCID) and is never referenced by the structure tree — that absence is exactly what separates it from real content. The optional property list can record the artifact's Type, a bounding box (BBox), and, for artifacts attached to the page edges, an Attached array naming the edges (such as Top or Bottom). This is the mechanism producers and accessibility tools rely on to classify page furniture precisely."
      ]
    },
    {
      "heading": "The three artifact types",
      "body": [
        "The PDF specification recognizes three broad artifact types. Pagination artifacts are the elements generated by paginating a document — running heads, running feet, and folios — that repeat from page to page. They may carry a further subtype identifying them as a header, a footer, or a watermark. Layout artifacts are purely typographic or visual devices used to arrange the page, such as rules, boxes, ruled table borders, column dividers, and background shading.",
        "Page artifacts are production aids attached to the physical sheet rather than to any logical content — cut marks, fold marks, color bars, and registration targets that belong to the printing process. Classifying an artifact into the correct type is not merely cosmetic: it lets downstream software reason about why the mark exists and treat, for example, a repeating page number differently from a one-off decorative flourish."
      ]
    },
    {
      "heading": "Why artifacts matter for accessibility",
      "body": [
        "The value of artifact marking shows up whenever a document is consumed by something other than a sighted reader looking at the full page. Screen readers walk the structure tree and skip artifacts, so the reading order stays free of repeated headers and folios. Reflow — rearranging a page to fit a narrow viewport — drops artifacts so the reader is not fed decorative clutter. Text extraction and copy operations produce cleaner output because page numbers and running heads are not interleaved with the body text.",
        "This is why artifact marking is central to a well-tagged, accessible PDF. The completeness principle behind accessible tagging is that all content must be either tagged as meaningful and reachable through the structure tree, or explicitly marked as an artifact. PDF/UA (ISO 14289), the standard for universally accessible PDF, builds directly on this dichotomy; content that is neither tagged nor artifacted is treated as a defect because a tool cannot know whether to read it or skip it."
      ]
    },
    {
      "heading": "Artifacts, decoration, and alternative text",
      "body": [
        "Artifacts are the PDF answer to purely decorative content. Where an author writing HTML might give a decorative image an empty alt attribute so a screen reader passes over it, the equivalent in a tagged PDF is to mark that image as an artifact. Because an artifact is understood to carry no meaning, it needs no alternative text at all — supplying alt text to an artifact would be contradictory, since the whole point is that assistive technology never reaches it.",
        "It is important not to confuse an artifact with untagged content. Simply leaving an element out of the structure tree does not make it an artifact; it makes it unclassified, which is a problem rather than a solution. An artifact is a deliberate, explicit declaration in the content stream. Deciding correctly which marks are meaningful and which are furniture is the human judgment at the heart of good tagging — and it is why automated tools can flag missing artifact marking but cannot always fix it unaided."
      ]
    }
  ],
  "keyFacts": [
    {
      "label": "Marked with",
      "value": "The Artifact tag inside BMC/BDC … EMC marked-content operators"
    },
    {
      "label": "Artifact types",
      "value": "Pagination, Layout, and Page"
    },
    {
      "label": "Pagination subtypes",
      "value": "Header, Footer, or Watermark"
    },
    {
      "label": "Structure link",
      "value": "None — artifacts carry no MCID and are excluded from the structure tree"
    }
  ],
  "specification": {
    "introduced": "PDF 1.4 (2001), as part of Tagged PDF",
    "iso": "ISO 32000-1:2008 / ISO 32000-2 (PDF 2.0)",
    "typicalUsage": "Marking page furniture — headers, footers, page numbers, decorative rules and backgrounds — so assistive technology, reflow and text extraction ignore it.",
    "relatedStandards": [
      "pdf-ua",
      "pdf-ua-1",
      "iso-32000",
      "pdf-2-0"
    ]
  },
  "misconceptions": [
    {
      "claim": "Marking content as an artifact hides it or removes it from the page.",
      "truth": "Artifacts still render on screen and still print unchanged. Artifact marking only affects logical status — it excludes the content from the structure tree, reading order and reflow, not from the visible page."
    },
    {
      "claim": "Artifacts should be given alternative text so screen readers describe them.",
      "truth": "Artifacts carry no meaning by definition, so they receive no alternative text. Assistive technology skips them entirely; adding alt text would contradict the reason the content was artifacted."
    },
    {
      "claim": "Leaving an element untagged is the same as marking it an artifact.",
      "truth": "Untagged content is unclassified and is treated as a defect. An artifact must be explicitly declared with the Artifact tag in the content stream; well-tagged PDF requires every mark to be either tagged content or an artifact."
    }
  ],
  "faq": [
    {
      "q": "Which operators mark an artifact in the content stream?",
      "a": "The marked-content operators. A sequence opens with BMC (or BDC when a property list is attached) using the Artifact tag and closes with EMC. BDC is used when you need to record a Type, Subtype, bounding box, or attached edges."
    },
    {
      "q": "Do artifacts appear in the structure tree?",
      "a": "No. Artifacts are deliberately kept out of the structure tree and are never assigned a marked-content identifier (MCID). That separation is what distinguishes them from real, meaningful content."
    },
    {
      "q": "Are artifacts still printed and visible?",
      "a": "Yes. Artifact marking changes only how the content is treated logically — by assistive technology, reflow and text extraction. The mark is rendered and printed exactly as it was before it was classified."
    },
    {
      "q": "Can an image be an artifact?",
      "a": "Yes. A purely decorative image, a background tint, or a watermark can be marked as an artifact so that assistive technology and reflow ignore it, rather than announcing or repositioning content that carries no meaning."
    },
    {
      "q": "What is the difference between a pagination artifact and a layout artifact?",
      "a": "Pagination artifacts are repeating page furniture generated by paginating the document — running headers, footers and page numbers. Layout artifacts are typographic decoration used to arrange a single page, such as rules, boxes, table borders and background shading."
    }
  ],
  "graph": {
    "parentConcept": "tagged-pdf",
    "relatedConcepts": [
      "logical-structure",
      "pdf-content-streams",
      "pdf-operators",
      "pdf-alt-text",
      "standard-structure-types",
      "untagged-pdf",
      "pdf-accessibility-checking",
      "role-mapping"
    ],
    "relatedStandards": [
      "pdf-ua",
      "pdf-ua-1",
      "iso-32000"
    ],
    "relatedTools": [
      {
        "label": "PDF Editor — Edit Text, Images and Pages on Mobile",
        "path": "/pdf-editor"
      }
    ],
    "relatedGuides": [
      {
        "label": "How to Prepare a PDF Before Sharing (Checklist)",
        "path": "/guides/how-to-prepare-pdf-before-sharing"
      }
    ]
  },
  "seeAlso": [
    "tagged-pdf",
    "marked-content",
    "marked-content-id",
    "pdf-structure-tree",
    "reading-order",
    "pdf-ua",
    "well-tagged-pdf",
    "structure-elements"
  ],
  "parentHub": {
    "label": "PDF Encyclopedia",
    "path": "/pdf-encyclopedia"
  }
};

export default content;
