import type { KnowledgeContent } from "@/types/content";

const content: KnowledgeContent = {
  "slug": "untagged-pdf",
  "h1": "Untagged PDF",
  "cluster": "accessibility",
  "aliases": [
    "non-tagged PDF",
    "PDF without tags",
    "unstructured PDF",
    "PDF without a structure tree"
  ],
  "definition": "An untagged PDF is a PDF without a logical structure tree, so its text and graphics carry no machine-readable information about reading order, headings, or document meaning.",
  "description": "An untagged PDF lacks the structure tree that defines reading order and semantics, so assistive tech and reflow have only the visual page layout to work from.",
  "searchIntent": "concept",
  "difficulty": "Beginner",
  "updated": "2026-07-04",
  "reviewed": "2026-07-04",
  "intro": [
    "At its core, a PDF describes a page as a set of drawing instructions: place this glyph here, fill this shape there. Those instructions produce an exact visual result, but they say nothing about what the content means. A tagged PDF adds an invisible layer on top of the visuals — a logical structure tree that marks headings, paragraphs, lists, tables, and their order. An untagged PDF simply does not have that layer.",
    "Because the structure is what carries meaning, an untagged file leaves software with only the visual arrangement to interpret. There are no semantic roles, no defined reading order, and no alternative text for images. The page still renders perfectly on screen and in print, so the difference is usually invisible to a sighted reader opening the file normally — it surfaces the moment a machine has to understand the document rather than just display it.",
    "It is worth separating two ideas that are often blurred together. An untagged PDF is not the same as a scanned or image-only PDF. A scanned file may contain only a picture of a page with no real text at all, while an untagged file frequently holds genuine, selectable text — it just lacks the structure that would explain how that text fits together."
  ],
  "sections": [
    {
      "heading": "What an Untagged PDF Contains",
      "body": [
        "An untagged PDF has the same building blocks as any other PDF: a document catalog, a page tree, and content streams full of positioned text and graphics operators. What it does not have is a structure tree. In a tagged file, the document catalog points to a structure tree root (StructTreeRoot) and a MarkInfo entry flags the document as marked; content is wrapped in marked-content sequences tied back to structure elements. In an untagged file those pieces are absent or the document is flagged as unmarked.",
        "The practical effect is that the content stream is the whole story. The order in which glyphs are drawn, and their coordinates on the page, are all a consumer has to work with. Nothing records that a run of large text is a heading, that a block of cells forms a table, or that a caption belongs to a nearby image. That information exists only in the mind of the reader looking at the rendered page."
      ]
    },
    {
      "heading": "How Software Handles Untagged Content",
      "body": [
        "When a program needs to consume an untagged PDF rather than just render it, it has to guess. To reconstruct reading order, it may follow the sequence of drawing operations in the content stream or analyze the geometry of text on the page. This works acceptably for simple single-column layouts and breaks down on multi-column pages, tables, sidebars, and footnotes, where the visual order and the drawing order can diverge sharply.",
        "This guessing is what shapes the real-world experience of untagged files. Screen readers and other assistive technologies can attempt an inferred reading order, but the results are inconsistent. Text extraction and copy-paste can jumble columns or interleave unrelated blocks. Reflowing content to fit a small screen is unreliable because the software has no authoritative order to reflow into. The visuals never change, but everything downstream of the visuals becomes fragile."
      ]
    },
    {
      "heading": "Why Tagging Is Often Absent",
      "body": [
        "Tagging is an optional feature, not an automatic property of the format, so many ordinary production paths yield untagged files. Print-to-PDF drivers and simple export routines frequently capture only the visual output. Older authoring tools predate widespread tagging support, and files converted or generated by lightweight libraries commonly skip it. Scanning paper to PDF produces an untagged (and often image-only) file unless structure is added afterward.",
        "Structure tagging was introduced to the format with tagged PDF in PDF 1.4, which means any file created without exercising that capability is untagged by default. In other words, an untagged PDF is usually the result of a workflow that never asked for tags, rather than a file where tags were deliberately removed — though tags can also be stripped during aggressive optimization or repair."
      ]
    },
    {
      "heading": "Accessibility and Standards Implications",
      "body": [
        "The absence of a structure tree is the central reason an untagged PDF is considered inaccessible. PDF/UA (ISO 14289) is the accessibility standard specifically for PDF, and tagging is foundational to it, so an untagged file cannot conform. When people evaluate document accessibility more broadly, WCAG and Section 508 are the frameworks most often referenced; each describes expectations that a tagged, well-structured document is designed to satisfy and that an untagged file is unable to meet on the merits of its structure alone.",
        "It helps to keep the scope narrow: untagged is a statement about logical structure, not about every quality of the file. An untagged PDF can still have accurate metadata, a specified language, working links, and fully selectable text. Those attributes live in separate parts of the file and neither create nor substitute for a structure tree."
      ]
    },
    {
      "heading": "From Untagged to Tagged",
      "body": [
        "Turning an untagged PDF into a tagged one means building the structure tree that was never there: identifying headings, paragraphs, lists, tables, reading order, and alternative text, then recording them as structure elements linked to the page content. Automated tagging can produce a first draft of this tree, but it infers structure from layout and can mislabel roles or misorder content, so the output is typically reviewed and corrected by hand.",
        "Because tags are separate from the drawing instructions, adding them does not change how the page looks — it adds the missing meaning underneath. For a fuller picture of the target state, see the entries on tagged PDF and what makes a well-tagged PDF, which describe the structure an untagged file is missing."
      ]
    }
  ],
  "keyFacts": [
    {
      "label": "Structure tree",
      "value": "Absent — no logical hierarchy of headings, paragraphs, lists, or tables"
    },
    {
      "label": "Visual rendering",
      "value": "Unaffected — a page looks identical whether tagged or not"
    },
    {
      "label": "PDF/UA (ISO 14289)",
      "value": "Cannot conform — accessible-PDF requirements depend on tagging"
    },
    {
      "label": "Text layer",
      "value": "May still be present and selectable; untagged is not the same as image-only"
    }
  ],
  "misconceptions": [
    {
      "claim": "An untagged PDF has no selectable text and can't be read at all.",
      "truth": "Untagged only means the structure tree is missing. The file can still contain a full, selectable text layer. Untagged is not the same as image-only or scanned."
    },
    {
      "claim": "Adding tags will change how the PDF looks.",
      "truth": "The structure tree is invisible and separate from the drawing instructions, so tagging a file adds meaning underneath without altering its visual appearance."
    },
    {
      "claim": "Every modern PDF is automatically tagged.",
      "truth": "Tagging is optional. Many export routines, print-to-PDF drivers, and older tools produce untagged files by default."
    }
  ],
  "faq": [
    {
      "q": "How can I tell whether a PDF is tagged or untagged?",
      "a": "Most PDF viewers report it in the document properties or an accessibility check, which looks for the structure tree root in the catalog and the MarkInfo flag in the file."
    },
    {
      "q": "Is an untagged PDF the same as a scanned or image-only PDF?",
      "a": "No. A scanned PDF may be only a picture of a page with no text at all, while an untagged PDF often contains real text but lacks structure. A file can be fully text-based and still untagged."
    },
    {
      "q": "Can an untagged PDF be turned into a tagged one?",
      "a": "Yes. Tools can generate a structure tree automatically, and the result is usually reviewed and corrected by hand, since automatic tagging can guess reading order or element roles incorrectly."
    },
    {
      "q": "Does untagged mean the PDF has no metadata?",
      "a": "No. Document metadata such as title, author, and language lives in separate dictionaries and can be present whether or not the file has a structure tree."
    },
    {
      "q": "Will a screen reader open an untagged PDF?",
      "a": "It can attempt to, but without tags it must infer reading order from the page layout, so results are inconsistent — especially with columns, tables, and complex layouts."
    }
  ],
  "graph": {
    "parentConcept": "tagged-pdf",
    "relatedConcepts": [
      "marked-content",
      "logical-structure",
      "structure-elements",
      "image-only-pdf",
      "searchable-pdf",
      "wcag-and-pdf",
      "section-508-and-pdf"
    ],
    "relatedStandards": [
      "pdf-ua",
      "pdf-ua-1"
    ],
    "relatedTools": [
      {
        "label": "PDF Editor — Edit Text, Images and Pages on Mobile",
        "path": "/pdf-editor"
      }
    ]
  },
  "seeAlso": [
    "tagged-pdf",
    "pdf-structure-tree",
    "reading-order",
    "screen-readers-and-pdf",
    "pdf-alt-text",
    "pdf-ua",
    "well-tagged-pdf",
    "pdf-accessibility-checking"
  ],
  "parentHub": {
    "label": "PDF Encyclopedia",
    "path": "/pdf-encyclopedia"
  }
};

export default content;
