import type { GuideContent } from "@/types/content";

const content: GuideContent = {
  slug: "why-wont-my-pdf-open",
  h1: "Why Won't My PDF Open? Causes and Practical Fixes",
  description:
    "A PDF that refuses to open is almost always one of five things. How to diagnose damaged downloads, password locks, viewer bugs and old files — and what fixes each.",
  updated: "2026-05-29",
  intro: [
    "You double-click a PDF and nothing happens. Or the viewer flashes an error, freezes, or pops up a password box you weren't expecting. PDFs feel like they should just work, and most of the time they do — so when one doesn't, it's worth knowing the short list of reasons why.",
    "There are really only a handful of causes behind a stubborn PDF: the download was incomplete, the file is password-protected, the viewer is mismatched to the PDF version, the file was generated by a buggy export, or it's a file format that only looks like a PDF. Each of those has a specific, repeatable fix.",
    "This guide walks the diagnoses one by one in the order they're worth checking, with the right tool for each. Most fixes are about identifying which problem you have, not learning some advanced trick.",
  ],
  steps: [
    {
      title: "Re-download the file before doing anything else",
      body: "A truncated download is the single most common reason a PDF won't open. Re-fetching the file fixes it in seconds. If it still fails, the file size matches the source, and the source still loads it — you've ruled out a bad download.",
    },
    {
      title: "Check whether it's password-protected",
      body: "Some viewers throw a generic error instead of a password prompt. If the file came from a bank, employer or legal vendor, assume there's a password. The original sender will know it.",
    },
    {
      title: "Try a different PDF viewer",
      body: "Browsers, Preview on macOS, Adobe Acrobat and mobile readers all parse PDFs slightly differently. A file one viewer refuses often opens fine in another. If a browser tab works but a desktop app doesn't, you're looking at a viewer-version mismatch, not a broken file.",
    },
    {
      title: "Inspect the actual file type",
      body: "Files arriving from email or chat sometimes carry a .pdf extension but are actually .docx, .html, an image or a ZIP. Opening with a generic text editor reveals the first few bytes. A real PDF starts with %PDF-. Anything else means rename or re-request.",
    },
    {
      title: "Repair through a re-export round-trip",
      body: "If the file is genuinely valid but broken in subtle ways, opening it in a viewer that can still display it and printing-to-PDF or exporting again often produces a clean copy. Some malformed objects get rewritten and the new file opens everywhere.",
    },
    {
      title: "Reduce its size if memory is the limit",
      body: "On older phones, very large scan-heavy PDFs can fail to open at all. Compress PDF in your browser shrinks the file in place; the compressed copy opens where the original wouldn't.",
    },
  ],
  tips: [
    "Compare the downloaded file size to whatever the sender posted. A mismatch points straight at a truncated download.",
    "If a browser opens the PDF but your desktop app doesn't, default it to open in the browser for now — you don't lose anything and you move on.",
    "A file that opens on phone but fails on laptop (or vice versa) is usually a viewer-version issue, not a corrupt file. Pick the viewer that works.",
    "When email-attached PDFs fail repeatedly, try downloading from the webmail interface rather than the desktop client — clients sometimes truncate large attachments.",
    "Save originals before doing repair round-trips. A bad re-export can lose form fields or annotations that the original kept.",
  ],
  mobileNote:
    "On a phone, the most common culprit is a partial download over flaky cellular. The PDF Editor app stores files locally and lets you re-fetch and open large PDFs without depending on browser caching, which is often where the truncation happens.",
  faq: [
    {
      q: "Why does my PDF say it's damaged when the sender says it's fine?",
      a: "Almost always a partial download. Re-fetch the file; check the byte size matches what the sender shared. If the new copy opens, the original copy was incomplete.",
    },
    {
      q: "My viewer asks for a password I don't have. What now?",
      a: "Only the original sender can share it. There's no safe way to bypass a real PDF password from the recipient side, and tools that promise it should be avoided.",
    },
    {
      q: "Why does it open in Chrome but not in Acrobat?",
      a: "Older desktop viewers may not support newer PDF features. Either keep using the viewer that works, or re-export the file through a print-to-PDF step to produce a compatible copy.",
    },
    {
      q: "Is there a tool that just 'fixes' broken PDFs?",
      a: "Sometimes — running the file through a re-export (open, print-to-PDF, save) cleans up minor structural issues. But severely corrupted PDFs are usually unrecoverable.",
    },
    {
      q: "Does compressing help with files that won't open?",
      a: "Only if the cause is memory: massive scan-heavy PDFs sometimes fail on older phones. Compress PDF makes them small enough to load. It won't fix a structurally broken file.",
    },
  ],
  related: [
    { label: "Compress PDF — shrink large files that won't open", path: "/compress-pdf" },
    { label: "PDF tools — full list of in-browser fixes", path: "/pdf-tools" },
    { label: "How to fix a corrupted PDF", path: "/guides/how-to-fix-a-corrupted-pdf" },
    { label: "How to fix PDF formatting problems", path: "/guides/how-to-fix-pdf-formatting-problems" },
  ],
  parentHub: { label: "PDF tools — free, browser-based", path: "/pdf-tools" },
};

export default content;
